import Head from 'next/head'
import GoogleLogin from 'react-google-login';

import styles from '../styles/Home.module.css';

const responseGoogle = (response) => {
    console.log(response);
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pdp-1-FE/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <GoogleLogin
              clientId="107088676671-v4932rhnac80bc4a26etvd4ulncu47go.apps.googleusercontent.com"
              buttonText="Login"
              onSuccess={responseGoogle}
              onFailure={responseGoogle}
              cookiePolicy={'single_host_origin'}
          />
      </main>
    <footer>
      </footer>
    </div>
  )
}
