import Head from 'next/head'
import GoogleAuth from "../components/Auth/GoogleAuth";

import styles from '../styles/Home.module.css';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pdp-1-FE/public/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>
    <footer>
      </footer>
    </div>
  )
}
